apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dynamicsecretconfigs.config.secretsengine.io
spec:
  group: config.secretsengine.io
  names:
    kind: DynamicSecretConfig
    plural: dynamicsecretconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            consul:
              properties:
                address:
                  type: string
                policy:
                  type: string
                tokenType:
                  type: string
              required:
              - address
              - tokenType
              - policy
              type: object
            password:
              properties:
                allowRepeatCharacters:
                  type: boolean
                disableUppercase:
                  type: boolean
                length:
                  format: int64
                  type: integer
                numDigits:
                  format: int64
                  type: integer
                numSymbols:
                  format: int64
                  type: integer
              required:
              - length
              type: object
            postgresql:
              properties:
                creation:
                  items:
                    type: string
                  type: array
                revocation:
                  items:
                    type: string
                  type: array
                uri:
                  type: string
              required:
              - uri
              - creation
              type: object
            rabbitmq:
              properties:
                tags:
                  items:
                    type: string
                  type: array
                uri:
                  type: string
                vhosts:
                  type: object
              required:
              - uri
              - tags
              - vhosts
              type: object
            secretName:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
