# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dynamicsecretconfig-sample

---

# Configure Password secrets engine
apiVersion: config.secretsengine.io/v1alpha1
kind: DynamicSecretConfig
metadata:
  name: password-secrets-engine
  namespace: dynamicsecretconfig-sample
spec:
  password:
    length: 10
    numSymbols: 5

---

# Provision randomly generated password
apiVersion: v1
kind: Secret
metadata:
  name: random-password-secret
  namespace: dynamicsecretconfig-sample
  annotations:
    secretsengine.io/dynamic-secret-config.name: password-secrets-engine
data: 
